### ISSUE TITLE
Ubuntu16.04 Link Error

### ISSUE THREAD

**Issue by freeyyc** [esmini/esmini#15]
[  4%] Building CXX object EnvironmentSimulator/CommonMini/CMakeFiles/CommonMini.dir/version.cpp.o
[  6%] Linking CXX static library libCommonMini.a
[ 10%] Built target CommonMini
[ 18%] Built target RoadManager
[ 52%] Built target ScenarioEngine
[ 54%] Linking CXX shared library libRoadManagerDLL.so
[ 56%] Built target RoadManagerDLL
[ 62%] Built target ViewerBase
[ 66%] Built target PlayerBase
[ 68%] Linking CXX shared library libScenarioEngineDLL.so
[ 70%] Built target ScenarioEngineDLL
[ 72%] Linking CXX executable ScenarioViewer
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcDefaultSubstitute’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcPatternDestroy’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcNameParse’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcInitLoadConfigAndFonts’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcFontMatch’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcConfigSubstitute’未定义的引用
../ScenarioEngineDLL/libScenarioEngineDLL.so：对‘FcPatternGetString’未定义的引用
collect2: error: ld returned 1 exit status
EnvironmentSimulator/ScenarioViewer/CMakeFiles/ScenarioViewer.dir/build.make:96: recipe for target 'EnvironmentSimulator/ScenarioViewer/ScenarioViewer' failed
make[2]: *** [EnvironmentSimulator/ScenarioViewer/ScenarioViewer] Error 1
CMakeFiles/Makefile2:475: recipe for target 'EnvironmentSimulator/ScenarioViewer/CMakeFiles/ScenarioViewer.dir/all' failed
make[1]: *** [EnvironmentSimulator/ScenarioViewer/CMakeFiles/ScenarioViewer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
yyc@yyc-HP-Z4-G4-Workstation:~/esmini/build$ 

"对‘FcDefaultSubstitute’未定义的引用" means "undefined reference to `FcDefaultSubstitute'"

**Comment by eknabevcc** [comment]
Thanks for valuable input! A few days ago we updated the OSG library package, for ongoing attempts to provide debug support as well. However it is work in progress and there seems to be some issue with that latest version of libraries. 
So I have now **restored last version of the [OpenSceneGraph_linux.7z](https://drive.google.com/uc?export=download&id=1OufA3TUQjBTkaRvAuo0rSUwryvoqde8G).
Please download and replace completely the content in folder externals/OpenSceneGraph.** 
I hope this will solve the issue. Please test and tell how it goes.

**Comment by eknabevcc** [comment]
By the way, I just noticed that you run Ubuntu version 16.04. I’ve only tested on Kubuntu 18.04 and Ubuntu 18.04. Not 16.04.
I would be interested to know whether you’ve previously got it to work and this link error is new since last few days, or if this was your first attempt to compile on 16.04?

**Comment by freeyyc** [comment]
thanks for your reply!
I have builded esmini successful with the osg library you provided.
This is my first time using it on ubuntu 16.04. 
Note: I have removed the -flto flag in the cmake file.

**Comment by eknabe** [comment]
Good to hear! The OSG library package I linked to is the very same (I have reverted to previous version) that is downloaded by cmake. So it should work when/if you clone the repo again.
Actually I have no clue, I don't remember, why we added that compiler flag, -flto. I can see it was added at this commit: https://github.com/esmini/esmini/commit/b247a8aa2868cb61242e3c18ae691ebb2be7dc55#diff-8caa55e4855ca7458abee412246404a0
But no explanation. So we will investigate further and maybe remove it altogether. Thanks for feedback.
